### ISSUE TITLE
Is there an image URL?

### ISSUE THREAD

**Issue by mb300sd** [LightningK0ala/satoshis.place#3]
Is there a URL to access the image directly?

**Comment by ekerstein** [comment]
https://github.com/LightningK0ala/satoshis.place/blob/master/README.md

I imagine it's the GET_LATEST_PIXELS event.

**Comment by mb300sd** [comment]
I got that already, but I'm hoping there's a HTTP url. I can't get any of 4 C# websocket libraries to connect, so I'm using my code to generate JS/HTML using socket.io and then open chrome to paint it.

**Comment by LightningK0ala** [comment]
I'm afraid there isn't, not familiar with any of the C# libraries. There's [online debugger](http://amritb.github.io/socketio-client-tool/?emitAs=JSON#url=aHR0cHM6Ly9hcGkuc2F0b3NoaXMucGxhY2U=&opt=&events=GET_SETTINGS,GET_SETTINGS_RESULT,BROADCAST_STATS) in case you need to debug

**Comment by LightningK0ala** [comment]
@mb300sd This might be coming soon actually.

I'm looking at the possibility to retire the GET_LATEST_PIXELS and GET_LATEST_PIXELS_RESULT call in favor of a URL for the image (hosted in S3). Since getting the board state is what requires the highest bandwidth usage, I'd like to offload that away from the API and let S3 handle it.

**Comment by LightningK0ala** [comment]
This feature wasn't built, the source code is open now so anyone is welcome to contribute / run their own.
